mysql:
  image: mysql:5.5
  container_name: database
  environment:
    MYSQL_ROOT_PASSWORD: "test123"
    MYSQL_DATABASE: "pippodb"
  volumes:
    - ./mysql_data:/var/lib/mysql

web:
  build: .
  container_name: website
  dockerfile: Dockerfile.web
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysql:db
  volumes:
    - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
    - ./files-www:/var/www/html
