# A apache + php container
FROM ubuntu:14.04

MAINTAINER Angelo D'Autilia <sydro@salug.it>

RUN apt-get update && \
    apt-get install -y php5 libapache2-mod-php5 php5-mysql php5-cli mysql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD files-www/index.html /var/www/html/
ADD files-www/immagine.jpg /var/www/html/
ADD apache2.conf /etc/apache2/apache2.conf

EXPOSE 80

WORKDIR /var/www/html

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
