mysql:
  build: .
  container_name: database
  dockerfile : Dockerfile.mysql
  volumes:
    - ./mysql_data:/var/lib/mysql

web:
  build: .
  container_name: website
  dockerfile: Dockerfile.web
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysql:db
  volumes:
    - ./configs/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
    - ./configs/php.ini:/etc/php5/apache2/php.ini
    - ./www/sito-online:/var/www/html
